#!/usr/bin/python3
import tkinter as tk
from PIL import Image, ImageTk

root = tk.Tk()
root.attributes('-fullscreen', True)
root.configure(background='black')
root.cursor = "none"

logo_path = "/usr/share/pixmaps/xfux-logo.png"

try:
    screen_width = root.winfo_screenwidth()
    screen_height = root.winfo_screenheight()

    img = Image.open(logo_path)
    # ZWIĘKSZONE LOGO: (800, 800)
    img = img.resize((800, 800), Image.Resampling.LANCZOS)
    photo = ImageTk.PhotoImage(img)

    label = tk.Label(root, image=photo, bg='black')
    label.place(relx=0.5, rely=0.5, anchor=tk.CENTER)
except Exception as e:
    # Jeśli logo nie istnieje, pokaże chociaż czarny ekran
    pass

root.after(4000, root.destroy)
root.mainloop()
